sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - dev
node_js:
  - "12"
  - "10"
  - "8"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
install:
  - npm install
  - npm prune
script:
  - make test-coveralls
